1. Series — негізгі тапсырмалар
temperatures деген Series жасаңыз. Ішінде қала температуралары болсын:
Алматы: 5
Астана: –3
Шымкент: 7
 Осы Series-ті экранға шығарыңыз.
Алматының температурасын индекстің көмегімен алыңыз.
Температурасы 0-ден жоғары қалаларды сүзіңіз.

In [ ]:
import pandas as pd
weather = {
    "Sity": ["Almaty", "Astana", "Shymkent"],
}
weather = pd.DataFrame(weather)

temperatures = pd.Series([5, -3, 7])
weather["Temperature"] = temperatures
weather

       Sity  Temperature
0    Almaty            5
1    Astana           -3
2  Shymkent            7

In [ ]:
print(weather.loc[0, 'Temperature'])

5

In [ ]:
filter = weather[weather["Temperature"] > 0]
filter

       Sity  Temperature
0    Almaty            5
2  Shymkent            7

2. DataFrame — кестемен жұмыс
Студенттер туралы DataFrame жасаңыз:
name
age
score
Aigerim
20
88
Dias
22
92
Miras
21
75
Dana
19
95


Жасы 20-дан жоғары студенттерді таңдаңыз.
Бағандарды тек name және score етіп шығарыңыз.
Ең жоғары балл жинаған студенттің атын табыңыз.

In [ ]:
students = {
    "name": ["Aigerim", "Dias", "Miras", "Dana"],
    "age": [20, 22, 21, 19],
    "score": [88, 92, 75, 95]
}
students = pd.DataFrame(students)
students

      name  age  score
0  Aigerim   20     88
1     Dias   22     92
2    Miras   21     75
3     Dana   19     95

In [ ]:
print(students[students["age"] > 20][["name", "score"]])

    name  score
1   Dias     92
2  Miras     75

In [ ]:
print(students.loc[students['score'].idxmax()]['name'])

Dana

3. Индексация және таңдау
iloc арқылы 3-жолдың 2-бағанын алыңыз.
loc көмегімен студенттің аты “Dias” болған жолды шығарыңыз.

In [ ]:
print(students.iloc[3,2])

In [ ]:
print(students.loc[students['name'] == 'Dias', ["name"]])

   name
1  Dias

4. Шарт бойынша сүзу
Дәрілер туралы DataFrame жасаңыз:
drug
price
amount
A
1200
5
B
800
10
C
600
3
D
2000
8

Тапсырмалар:
Бағасы 1000 теңгеден қымбат дәрілерді шығарыңыз.


Бағасы 600-800 аралығындағы дәрілерді таңдаңыз.


Қордағы саны (amount) 5-тен аз дәрілерді шығарыңыз.

In [ ]:
drugs_df = {
    "drug": ["A", "B", "C", "D"],
    "price": [1200, 800, 600, 2000],
    "amount": [5, 10, 3, 8]
}
drugs_df = pd.DataFrame(drugs_df)

filter1 = drugs_df[drugs_df["price"] > 1000]
filter2 = drugs_df[(drugs_df["price"] <= 800) & (drugs_df["price"] >= 600)]
filter3 = drugs_df[drugs_df["amount"] < 5]
print(f'Бағасы 1000 тг-ден жоғары дәрілер:\n\n{filter1}\n')
print(f'Бағасы 600-800 аралығындағы дәрілер:\n\n{filter2}\n')
print(f'Қордағы саны (amount) 5-тен аз дәрілер:\n\n{filter3}\n')

Бағасы 1000 тг-ден жоғары дәрілер:

  drug  price  amount
0    A   1200       5
3    D   2000       8

Бағасы 600-800 аралығындағы дәрілер:

  drug  price  amount
1    B    800      10
2    C    600       3

Қордағы саны (amount) 5-тен аз дәрілер:

  drug  price  amount
2    C    600       3

5. Groupby — топтастыру
Қызметкерлер кестесін жасаңыз:
name
department
salary
Ayan
IT
400000
Dana
HR
300000
Miras
IT
450000
Aida
HR
320000
Timur
Sales
280000

Тапсырмалар:
Әр бөлім бойынша орташа жалақыны есептеңіз.
Әр бөлімдегі қызметкерлер санын шығарыңыз.
Ең жоғары жалақысы бар бөлімді анықтаңыз.

In [ ]:
employees = {
    "name": ["Ayan", "Dana", "Miras", "Aida", "Timur"],
    "department": ["IT", "HR", "IT", "HR", "Sales"],
    "salary": [400000, 300000, 450000, 320000, 280000]
}
employees = pd.DataFrame(employees)

grouped_mean = employees.groupby('department')['salary'].mean()
print(f'Әр бөлім бойынша орташа жалақы:\n\n{grouped_mean}\n')

grouped_sum = employees.groupby('department')['department'].count()
print(f'Әр бөлімдегі қызметкерлер саны: \n\n{grouped_sum}\n')

grouped_max = employees.groupby('department')['salary'].max()
print(f'Әр бөлім бойынша ең жоғары жалақы: \n\n{grouped_max}\n')

max_salary = grouped_max.max()
print(f'Ең жоғары жалақысы бар бөлім: {grouped_max.idxmax()} ({max_salary} KZT)')

Әр бөлім бойынша орташа жалақы:

department
HR       310000.0
IT       425000.0
Sales    280000.0
Name: salary, dtype: float64

Әр бөлімдегі қызметкерлер саны:

department
HR       2
IT       2
Sales    1
Name: department, dtype: int64

Әр бөлім бойынша ең жоғары жалақы:

department
HR       320000
IT       450000
Sales    280000
Name: salary, dtype: int64

Ең жоғары жалақысы бар бөлім: IT (450000 KZT)

6. Агрегаттау (sum, mean, max, min)
Берілген кестеге сүйеніп:
Әр бөлім үшін жалақының ең кішісі мен ең жоғарғысын табыңыз.
Әр топтағы жалақының суммасын есептеңіз.

In [ ]:
grouped_min = employees.groupby('department')['salary'].min()
print(f'Әр бөлім бойынша ең кіші жалақы: \n{grouped_min}\n')

min_salary = grouped_min.min()
print(f'Ең кіші жалақысы бар бөлім: {grouped_min.idxmin()} ({min_salary} KZT)\n')

group_salary_sum = employees.groupby('department')['salary'].sum()
print(f'Әр топтағы жалақының суммасы:\n{group_salary_sum}')

Әр бөлім бойынша ең кіші жалақы:
department
HR       300000
IT       400000
Sales    280000
Name: salary, dtype: int64

Ең кіші жалақысы бар бөлім: Sales (280000 KZT)

Әр топтағы жалақының суммасы:
department
HR       620000
IT       850000
Sales    280000
Name: salary, dtype: int64

7. Кестелерді біріктіру (merge, join, concat)
Берілген екі кесте:
students:
id
name
1
Aigerim
2
Dias
3
Ayan

scores:
id
math
physics
1
88
90
2
75
80
3
95
92

Тапсырмалар:
Екі кестені id бойынша біріктіріңіз (merge).
Индексті id етіп қойып, join() қолданып біріктіріңіз.
concat() қолданып students кестесін екі рет артынан қосыңыз.
concat(axis=1) қолданып students және scores кестесін бүйірінен біріктіріңіз.

In [ ]:
students2 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Aigerim", "Dias", "Ayan", "Sara"],
})
scores = pd.DataFrame({
    "id": [1, 2, 3, 5],
    "math": [88, 75, 95, 92],
    "physics": [90, 80, 92, 87]
})
merged1 = pd.merge(students2, scores, on = "id")
print(f'Екі кестені id бойынша біріктіру:\n{merged1}\n')

merged2 = pd.merge(students2, scores, on = "id", how = "right")
print(f'Екі кестені merge(right) бойынша біріктіру:\n{merged2}\n')

merged3 = pd.merge(students2, scores, on = "id", how = "left")
print(f'Екі кестені merge(left) бойынша біріктіру:\n{merged3}\n')

merged4 = pd.merge(students2, scores, on = "id", how = "outer")
print(f'Екі кестені merge(outer) бойынша біріктіру:\n{merged4}\n')

Екі кестені id бойынша біріктіру:
   id     name  math  physics
0   1  Aigerim    88       90
1   2     Dias    75       80
2   3     Ayan    95       92

Екі кестені merge(right) бойынша біріктіру:
   id     name  math  physics
0   1  Aigerim    88       90
1   2     Dias    75       80
2   3     Ayan    95       92
3   5      NaN    92       87

Екі кестені merge(left) бойынша біріктіру:
   id     name  math  physics
0   1  Aigerim  88.0     90.0
1   2     Dias  75.0     80.0
2   3     Ayan  95.0     92.0
3   4     Sara   NaN      NaN

Екі кестені merge(outer) бойынша біріктіру:
   id     name  math  physics
0   1  Aigerim  88.0     90.0
1   2     Dias  75.0     80.0
2   3     Ayan  95.0     92.0
3   4     Sara   NaN      NaN
4   5      NaN  92.0     87.0

In [ ]:
join_left = students2.set_index("id")
join_right = scores.set_index("id")

result_left = join_left.join(join_right)
print("Left Join:\n", result_left)

result_inner = join_left.join(join_right, how='inner')
print("\nInner Join:\n", result_inner)

Left Join:
        name  math  physics
id
1   Aigerim  88.0     90.0
2      Dias  75.0     80.0
3      Ayan  95.0     92.0
4      Sara   NaN      NaN

Inner Join:
        name  math  physics
id
1   Aigerim    88       90
2      Dias    75       80
3      Ayan    95       92

In [ ]:
concat1 = pd.concat([students2, students2])
print(f'concat() қолданып students кестесін екі рет артынан қосу:\n{concat1}')

concat() қолданып students кестесін екі рет артынан қосу:
   id     name
0   1  Aigerim
1   2     Dias
2   3     Ayan
3   4     Sara
0   1  Aigerim
1   2     Dias
2   3     Ayan
3   4     Sara

In [ ]:
concat2 = pd.concat([students2, students2], axis=1)
print(f'concat(axis=1) қолданып students және scores кестесін бүйірінен біріктір:\n{concat2}')

concat(axis=1) қолданып students және scores кестесін бүйірінен біріктір:
   id     name  id     name
0   1  Aigerim   1  Aigerim
1   2     Dias   2     Dias
2   3     Ayan   3     Ayan
3   4     Sara   4     Sara

8. Қиынырақ деңгей:
Төмендегі DataFrame бойынша әр пәннен жалпы статистика (min, max, mean, median) жасаңыз:
student
math
physics
history
Aigerim
88
90
78
Dias
75
80
85
Ayan
95
92
90


Әр студенттің орташа балын есептеп, жаңа avg бағанын қосыңыз.
Орташа балы 85-тен жоғары студенттерді таңдаңыз.

In [ ]:
df3 = pd.DataFrame({
    "student": ["Aigerim", "Dias", "Ayan"],
    "math": [88, 75, 95],
    "physics": [90, 80, 92],
    "history": [78, 85, 90]
})
print(f'DataFrame бойынша әр пәннен жалпы статистика:\n{df3.describe()}\n')

df3['avg'] = df3[['math', 'physics', 'history']].mean(axis=1)
print(f'Әр студенттің орташа балы бар жаңа DataFrame:\n{df3}\n')

high_avg_students = df3[df3['avg'] > 85]
print(f'Орташа балы 85-тен жоғары студенттер:\n{high_avg_students}')

DataFrame бойынша әр пәннен жалпы статистика:
            math    physics    history
count   3.000000   3.000000   3.000000
mean   86.000000  87.333333  84.333333
std    10.148892   6.429101   6.027714
min    75.000000  80.000000  78.000000
25%    81.500000  85.000000  81.500000
50%    88.000000  90.000000  85.000000
75%    91.500000  91.000000  87.500000
max    95.000000  92.000000  90.000000

Әр студенттің орташа балы бар жаңа DataFrame:
   student  math  physics  history        avg
0  Aigerim    88       90       78  85.333333
1     Dias    75       80       85  80.000000
2     Ayan    95       92       90  92.333333

Орташа балы 85-тен жоғары студенттер:
   student  math  physics  history        avg
0  Aigerim    88       90       78  85.333333
2     Ayan    95       92       90  92.333333